package com.example.application.views.записатьсянакурсы;

import com.example.application.views.MainLayout;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.ResponsiveStep;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.H4;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;

@PageTitle("Записаться на курсы")
@Route(value = "", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class ЗаписатьсянакурсыView extends Composite<VerticalLayout> {

    public ЗаписатьсянакурсыView() {
        H1 h1 = new H1();
        H4 h4 = new H4();
        Hr hr = new Hr();
        H1 h12 = new H1();
        Hr hr2 = new Hr();
        FormLayout formLayout3Col = new FormLayout();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H2 h2 = new H2();
        Hr hr3 = new Hr();
        H3 h3 = new H3();
        H4 h42 = new H4();
        Hr hr4 = new Hr();
        Button buttonPrimary = new Button();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H2 h22 = new H2();
        Hr hr5 = new Hr();
        H3 h32 = new H3();
        H4 h43 = new H4();
        Hr hr6 = new Hr();
        Button buttonPrimary2 = new Button();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H2 h23 = new H2();
        Hr hr7 = new Hr();
        H3 h33 = new H3();
        H4 h44 = new H4();
        Hr hr8 = new Hr();
        Button buttonPrimary3 = new Button();
        Hr hr9 = new Hr();
        H1 h13 = new H1();
        Hr hr10 = new Hr();
        FormLayout formLayout3Col2 = new FormLayout();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        H2 h24 = new H2();
        Hr hr11 = new Hr();
        H3 h34 = new H3();
        H4 h45 = new H4();
        Hr hr12 = new Hr();
        Button buttonPrimary4 = new Button();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        H2 h25 = new H2();
        Hr hr13 = new Hr();
        H3 h35 = new H3();
        H4 h46 = new H4();
        Hr hr14 = new Hr();
        Button buttonPrimary5 = new Button();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        H2 h26 = new H2();
        Hr hr15 = new Hr();
        H3 h36 = new H3();
        H4 h47 = new H4();
        Hr hr16 = new Hr();
        Button buttonPrimary6 = new Button();
        Hr hr17 = new Hr();
        H2 h27 = new H2();
        Hr hr18 = new Hr();
        getContent().setWidth("100%");
        getContent().setHeight("1500px");
        h1.setText("CodeRu");
        h1.setWidth("max-content");
        h4.setText(
                "Добро пожаловать в CodeRu - ваше онлайн-назначение для обучения программированию! Мы предлагаем широкий спектр курсов, от основ Java до продвинутого разработки в Unreal Engine. Наша миссия - сделать обучение программированию увлекательным, доступным и эффективным.\r\n\r\nВыберите один из наших курсов ниже, чтобы начать свой путь в мире программирования. У нас есть что-то для всех, независимо от вашего уровня опыта и интересов.\r\n\r\nКурсы доступны онлайн, 24/7, чтобы вы могли учиться в удобное для вас время и темп. Не упустите возможность расширить свои знания и навыки вместе с CodeRu!");
        h4.setWidth("100%");
        hr.setHeight("10px");
        h12.setText("</> Языки программирования:");
        h12.setWidth("max-content");
        hr2.setHeight("10px");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, formLayout3Col);
        formLayout3Col.setWidth("100%");
        formLayout3Col.setResponsiveSteps(new ResponsiveStep("0", 1), new ResponsiveStep("250px", 2),
                new ResponsiveStep("500px", 3));
        layoutColumn2.setHeightFull();
        formLayout3Col.setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("350px");
        layoutColumn2.setHeight("450px");
        layoutColumn2.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn2.setAlignItems(Alignment.START);
        h2.setText("??‍? Java");
        h2.setWidth("max-content");
        h3.setText("Описание:");
        h3.setWidth("100%");
        h42.setText(
                "Узнайте все о разработке приложений на языке Java – от основ до продвинутых техник. Этот курс охватывает основные концепции ООП, структуры данных, алгоритмы и современные инструменты разработки.");
        h42.setWidth("100%");
        buttonPrimary.setText("Записаться на курс");
        layoutColumn2.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary);
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutColumn3.setHeightFull();
        formLayout3Col.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("350px");
        layoutColumn3.setHeight("450px");
        layoutColumn3.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn3.setAlignItems(Alignment.CENTER);
        h22.setText("#️⃣ Python");
        layoutColumn3.setAlignSelf(FlexComponent.Alignment.START, h22);
        h22.setWidth("max-content");
        h32.setText("Описание:");
        layoutColumn3.setAlignSelf(FlexComponent.Alignment.START, h32);
        h32.setWidth("max-content");
        h43.setText(
                "Python – это мощный язык программирования, который используется в различных областях: от веб-разработки до машинного обучения. В этом курсе вы изучите базовые и продвинутые темы, а также получите практический опыт.");
        layoutColumn3.setAlignSelf(FlexComponent.Alignment.START, h43);
        h43.setWidth("100%");
        buttonPrimary2.setText("Записаться на курс");
        layoutColumn3.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary2);
        buttonPrimary2.setWidth("min-content");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutColumn4.setHeightFull();
        formLayout3Col.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("350px");
        layoutColumn4.setHeight("450px");
        h23.setText("</> JavaScript");
        h23.setWidth("max-content");
        h33.setText("Описание:");
        h33.setWidth("max-content");
        h44.setText(
                "Этот курс поможет вам стать фронтенд разработчиком. Вы изучите основы JavaScript, работу с DOM, а также популярные библиотеки и фреймворки, такие как React и Vue.js.");
        h44.setWidth("100%");
        buttonPrimary3.setText("Записаться на курс");
        layoutColumn4.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary3);
        buttonPrimary3.setWidth("min-content");
        buttonPrimary3.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        hr9.setHeight("10px");
        h13.setText("?️ Игровые движки:");
        h13.setWidth("max-content");
        hr10.setHeight("10px");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, formLayout3Col2);
        formLayout3Col2.setWidth("100%");
        formLayout3Col2.setResponsiveSteps(new ResponsiveStep("0", 1), new ResponsiveStep("250px", 2),
                new ResponsiveStep("500px", 3));
        layoutColumn5.setHeightFull();
        formLayout3Col2.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("350px");
        layoutColumn5.setHeight("450px");
        layoutColumn5.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn5.setAlignItems(Alignment.START);
        h24.setText("??‍? Unreal Engine");
        h24.setWidth("max-content");
        h34.setText("Описание:");
        h34.setWidth("100%");
        h45.setText(
                "Погрузитесь в мир разработки игр с помощью Unreal Engine. Узнайте, как создавать потрясающие 3D игры и интерактивные приложения, используя мощные инструменты и возможности этого движка.");
        h45.setWidth("100%");
        buttonPrimary4.setText("Записаться на курс");
        layoutColumn5.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary4);
        buttonPrimary4.setWidth("min-content");
        buttonPrimary4.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutColumn6.setHeightFull();
        formLayout3Col2.setFlexGrow(1.0, layoutColumn6);
        layoutColumn6.setWidth("350px");
        layoutColumn6.setHeight("450px");
        layoutColumn6.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn6.setAlignItems(Alignment.CENTER);
        h25.setText("?‍? Unity");
        layoutColumn6.setAlignSelf(FlexComponent.Alignment.START, h25);
        h25.setWidth("max-content");
        h35.setText("Описание:");
        layoutColumn6.setAlignSelf(FlexComponent.Alignment.START, h35);
        h35.setWidth("max-content");
        h46.setText(
                "Изучите основы и продвинутые возможности Unity – одного из самых популярных движков для создания 2D и 3D игр. В этом курсе вы освоите C#, анимацию, физику, работу с 3D моделями и многое другое.");
        layoutColumn6.setAlignSelf(FlexComponent.Alignment.START, h46);
        h46.setWidth("100%");
        buttonPrimary5.setText("Записаться на курс");
        layoutColumn6.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary5);
        buttonPrimary5.setWidth("min-content");
        buttonPrimary5.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutColumn7.setHeightFull();
        formLayout3Col2.setFlexGrow(1.0, layoutColumn7);
        layoutColumn7.setWidth("350px");
        layoutColumn7.setHeight("450px");
        h26.setText("? Godot Engine");
        h26.setWidth("max-content");
        h36.setText("Описание:");
        h36.setWidth("max-content");
        h47.setText(
                "Откройте для себя Godot Engine – гибкий и мощный инструмент для создания игр с открытым исходным кодом. Этот курс охватывает все аспекты разработки игр, включая работу с GDScript, анимацию, физику и пользовательский интерфейс.");
        h47.setWidth("100%");
        buttonPrimary6.setText("Записаться на курс");
        layoutColumn7.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary6);
        buttonPrimary6.setWidth("min-content");
        buttonPrimary6.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        hr17.setHeight("10px");
        h27.setText("Обучайтесь вместе с CodeRu, открывая новые горизонты!");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, h27);
        h27.setWidth("max-content");
        hr18.setHeight("10px");
        getContent().add(h1);
        getContent().add(h4);
        getContent().add(hr);
        getContent().add(h12);
        getContent().add(hr2);
        getContent().add(formLayout3Col);
        formLayout3Col.add(layoutColumn2);
        layoutColumn2.add(h2);
        layoutColumn2.add(hr3);
        layoutColumn2.add(h3);
        layoutColumn2.add(h42);
        layoutColumn2.add(hr4);
        layoutColumn2.add(buttonPrimary);
        formLayout3Col.add(layoutColumn3);
        layoutColumn3.add(h22);
        layoutColumn3.add(hr5);
        layoutColumn3.add(h32);
        layoutColumn3.add(h43);
        layoutColumn3.add(hr6);
        layoutColumn3.add(buttonPrimary2);
        formLayout3Col.add(layoutColumn4);
        layoutColumn4.add(h23);
        layoutColumn4.add(hr7);
        layoutColumn4.add(h33);
        layoutColumn4.add(h44);
        layoutColumn4.add(hr8);
        layoutColumn4.add(buttonPrimary3);
        getContent().add(hr9);
        getContent().add(h13);
        getContent().add(hr10);
        getContent().add(formLayout3Col2);
        formLayout3Col2.add(layoutColumn5);
        layoutColumn5.add(h24);
        layoutColumn5.add(hr11);
        layoutColumn5.add(h34);
        layoutColumn5.add(h45);
        layoutColumn5.add(hr12);
        layoutColumn5.add(buttonPrimary4);
        formLayout3Col2.add(layoutColumn6);
        layoutColumn6.add(h25);
        layoutColumn6.add(hr13);
        layoutColumn6.add(h35);
        layoutColumn6.add(h46);
        layoutColumn6.add(hr14);
        layoutColumn6.add(buttonPrimary5);
        formLayout3Col2.add(layoutColumn7);
        layoutColumn7.add(h26);
        layoutColumn7.add(hr15);
        layoutColumn7.add(h36);
        layoutColumn7.add(h47);
        layoutColumn7.add(hr16);
        layoutColumn7.add(buttonPrimary6);
        getContent().add(hr17);
        getContent().add(h27);
        getContent().add(hr18);
    }
}
